"""empty message

Revision ID: 1bdbad105b3c
Revises: 
Create Date: 2019-06-19 08:56:43.759943

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bdbad105b3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolschema',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tags',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('protocols',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('protocol', sa.JSON(), nullable=False),
    sa.Column('protocolschema', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['protocolschema'], ['protocolschema.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('tags_protocol',
    sa.Column('tags_uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('protocol_uuid', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['protocol_uuid'], ['protocols.uuid'], ),
    sa.ForeignKeyConstraint(['tags_uuid'], ['tags.uuid'], ),
    sa.PrimaryKeyConstraint('tags_uuid', 'protocol_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags_protocol')
    op.drop_table('protocols')
    op.drop_table('tags')
    op.drop_table('protocolschema')
    # ### end Alembic commands ###
